# permissions for end users to view loggrabbers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: loggrabber-viewer-role
rules:
- apiGroups:
  - cache.loggrabber.io
  resources:
  - loggrabbers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cache.loggrabber.io
  resources:
  - loggrabbers/status
  verbs:
  - get
