---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - cache.loggrabber.io
  resources:
  - loggrabbers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.loggrabber.io
  resources:
  - loggrabbers/finalizers
  verbs:
  - update
- apiGroups:
  - cache.loggrabber.io
  resources:
  - loggrabbers/status
  verbs:
  - get
  - patch
  - update
