apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: lograbber-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Loggrabber is the Schema for the loggrabbers API
      displayName: Loggrabber
      kind: Loggrabber
      name: loggrabbers.cache.loggrabber.io
      version: v1alpha1
  description: LogGrabber is a automated log extractor and log component manager
  displayName: loggrabber
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - log
  - extractor
  - manager
  - loglevel
  links:
  - name: Lograbber Operator
    url: https://lograbber-operator.domain
  maturity: alpha
  provider:
    name: Red Hat
  version: 0.0.0
